---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

**loading Libraries**

```{r packages, echo=TRUE, warning=FALSE, message=FALSE}

  library(tidyverse)
  library(ggplot2)

```


**Reading dataset and processing data**

```{r loaddata, echo=TRUE}

                if (file.exists("activity.csv")) {
                  print("Activity Data Loaded")
                } else {
                  unzip("activity.zip")
                  print("Unzipped & Loaded Activity Data")
                }
# Cleanup data
                activity_dta <-  read.csv("activity.csv") 

                activity_dta$date <- as.Date(activity_dta$date)
                         actByDate <- activity_dta %>% 
                                        na.omit() %>%
                                  group_by(date) %>%
                                        summarize(daily_steps = sum(steps))
                                        print(head(actByDate))

```

**Histogram of the total number of steps taken each day**

```{r hist}
                ggplot(data = actByDate,
                      aes(x = daily_steps)) +
                      geom_histogram(binwidth = 1000,
                                     fill = "seagreen",
                                     color = "orange") +
                                     xlab("Daily Steps")+
                                     ylab("Frequency")

```

**Mean and median number of steps taken each day**

```{r meanactivity, echo=TRUE}

                paste0("mean total number of steps taken per day =  ", mean(actByDate$daily_steps))

                paste0("average number of steps taken per day =  ", median(actByDate$daily_steps))

```

**Average Daily activity pattern**
```{r avg_pattern}
                
                actByInterval <- activity_dta %>% 
                                    na.omit() %>%
                              group_by(interval) %>%
                                        summarize(daily_avge = mean(steps))
                                        print(head(actByInterval))
                                        
# Time series of daily steps             
                                        
                activity_ts <- actByDate %>% ts()     
                               print(head(activity_ts))
                                        

                # ggplot(activity_dta, aes(x = interval))


```

**Code to describe and show a strategy for imputing missing data**

```{r NAValues}
                 sum(is.na(activity_dta))

```

## Are there differences in activity patterns between weekdays and weekends?
